
networks:
   schoolwebapiapp:

services:

  SqlServerDb:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
        - 8002:1433
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=s@password2407
    networks:
        - schoolwebapiapp 
  SchoolsWebApi:
    container_name: schoolswebapi-app
    image: ${DOCKER_REGISTRY-}schoolwebapi
    ports:
        - 5011:8080
    build:
        context: .
        dockerfile: Schools.WebApi/Dockerfile
    networks:
        - schoolwebapiapp
    depends_on:
        - SqlServerDb



